# These are supported funding model platforms

# GitHub Sponsors (máximo 4 usuarios)
github: [VictorCast2]

# Buy Me a Coffee
buy_me_a_coffee: victorcast2

# thanks.dev
thanks_dev: victorcast2

# Enlaces personalizados (máximo 4 URLs)
custom: ['https://paypal.me/VictorCast2']
