version: '3.9'

services:
  app:
    image: buques-app
    container_name: buques-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    networks:
      - buques-network

  mongodb:
    image: mongo:latest
    container_name: mongo-buques
    environment:
      - MONGO_INITDB_DATABASE=GestionBuques
    ports:
      - "27017:27017"
    networks:
      - buques-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis-buques
    ports:
      - "6379:6379"
    networks:
      - buques-network
    volumes:
      - redis_data:/data

networks:
  buques-network:

volumes:
  mongodb_data:
  redis_data: