version: '3.9'

services:
  app:
    image: buques-app
    container_name: buques-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
        - mongodb
        - redis
    environment:
        - MONGODB_DATABASE=GestionBuques
        - MONGODB_URI=mongodb://mongodb:27017/GestionBuques
        - REDIS_HOST=localhost
        - REDIS_URI=redis://localhost:6379/Usuarios
        - REDIS_DATABASE=Usuarios
        - REDIS_PORT=6379
    env_file:
        - .env
    networks:
        - buques-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  mongodb:
    image: mongo:latest
    container_name: mongo-buques
    environment:
      - MONGODB_DATABASE=GestionBuques
      - MONGODB_URI=mongodb://mongodb:27017/GestionBuques
    ports:
      - "27017:27017"
    networks:
      - buques-network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping')" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  redis:
    image: redis:latest
    container_name: redis-buques
    ports:
      - "6379:6379"
    networks:
      - buques-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  buques-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: