version: '3.9'

services:
  app:
    image: buques-app
    container_name: buques-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - JWT_SECRET_BUQUES=LLAVE_TEMP_DEV
      - JWT_ISSUER_BUQUES=USER_TEMP_DEV
      - REDISHOST=redis
      - REDISPASS=redispassword
      - REDISPORT=6379
    networks:
      - buques-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  redis:
    image: redis:7.2-alpine
    container_name: redis-container
    restart: always
    command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"
    networks:
      - buques-network
    volumes:
      - redis-data:/data

networks:
  buques-network:
    driver: bridge

volumes:
  redis-data: