version: '3.8'

services:
  app:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/GestionBuques
      - MONGODB_DATABASE=GestionBuques
      - JWT_SECRET_BUQUES=LLAVE_TEMP_DEV
      - JWT_ISSUER_BUQUES=USER_TEMP_DEV
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TIMEOUT=60000
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=GestionBuques
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"