spring.application.name=GestionBuques

# Configuracion del servidor
server.port=8080

# Configuracion de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/prueba_gestionBuquesDB?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=0220

# Configuracion de JPA
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect.storage_engine=innodb

# Configuracion de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5