-- MySQL Script generated by MySQL Workbench
-- Sun Apr  6 00:45:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_Buque
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_Buque` ;

-- -----------------------------------------------------
-- Schema DB_Buque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Buque` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `DB_Buque` ;

-- -----------------------------------------------------
-- Table `Buques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Buques` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Buques` (
  `id_buque` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_muelle` INT NOT NULL,
  `id_proceso` INT NOT NULL,
  `imagen` BLOB NULL,
  `matricula` VARCHAR(175) NOT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `tipo_buque` VARCHAR(75) NOT NULL,
  `peso` DOUBLE NOT NULL,
  `largo` DOUBLE NOT NULL,
  `ancho` DOUBLE NOT NULL,
  PRIMARY KEY (`id_buque`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `matricula_UNIQUE` ON `Buques` (`matricula` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Detalle_Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Detalle_Factura` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Detalle_Factura` (
  `id_Detalle` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NOT NULL,
  `descipcion_servicio` VARCHAR(275) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` INT NOT NULL,
  `subtotal` INT NOT NULL,
  PRIMARY KEY (`id_Detalle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empresas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empresas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `NIT` VARCHAR(75) NOT NULL,
  `nombre` VARCHAR(250) NOT NULL,
  `pais` VARCHAR(175) NOT NULL,
  `ciudad` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(250) NOT NULL,
  `cantidad_buques` INT NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `correo_UNIQUE` ON `Empresas` (`correo` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `direccion_UNIQUE` ON `Empresas` (`direccion` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Factura` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Factura` (
  `Id_factura` INT NOT NULL AUTO_INCREMENT,
  `Empresas_id_empresa` INT NOT NULL,
  `total` INT NOT NULL,
  `iva` INT NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `estado` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`Id_factura`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Inspeccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inspeccion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Inspeccion` (
  `id_inspeccion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_Buque` INT NOT NULL,
  `fecha_inspeccion` DATE NOT NULL,
  `resultado` VARCHAR(75) NOT NULL,
  `observaciones` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_inspeccion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Maquinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Maquinas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Maquinas` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `id_muelle` INT NOT NULL,
  `nombre` VARCHAR(175) NOT NULL,
  `estado` VARCHAR(75) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_equipo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Muelle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Muelle` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Muelle` (
  `id_muelle` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `capacidadBuques` INT NOT NULL,
  `capacidad` INT NOT NULL,
  `estado` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_muelle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Procesos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Procesos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Procesos` (
  `id_proceso` INT NOT NULL,
  `tipo_operacion` VARCHAR(75) NOT NULL,
  `tipo_carga` VARCHAR(150) NOT NULL,
  `tipo_producto` VARCHAR(150) NOT NULL,
  `cantidadProducto` BIGINT NOT NULL,
  `peso_total` BIGINT NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_proceso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Solicitud_Atraque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Solicitud_Atraque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Solicitud_Atraque` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `Buques_id_Buque` INT NOT NULL,
  `fecha_llegada` DATETIME NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `estado_solicitud` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_solicitud`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `id_empresa` INT NOT NULL,
  `tipo_identificacion` VARCHAR(100) NOT NULL,
  `numero_identificacion` INT NOT NULL,
  `nombres` VARCHAR(250) NOT NULL,
  `apellidos` VARCHAR(250) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(250) NOT NULL,
  `contraseña` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `cedula_UNIQUE` ON `Usuarios` (`numero_identificacion` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;